# Generated by Django 5.2.7 on 2025-11-05 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_commentvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='edited_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when comment was last edited', null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='is_edited',
            field=models.BooleanField(default=False, help_text='Whether the comment has been edited'),
        ),
        migrations.AddField(
            model_name='post',
            name='edited_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when post was last edited', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='is_edited',
            field=models.BooleanField(default=False, help_text='Whether the post has been edited'),
        ),
    ]
