from django.contrib import admin
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from community import views as community_views
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

# Create a router instance
router = DefaultRouter()
router.register(r'posts', community_views.PostViewSet)
router.register(r'comments', community_views.CommentViewSet)
router.register(r'notifications', community_views.NotificationViewSet, basename='notification')

urlpatterns = [
    path('admin/', admin.site.urls),
    
    # --- API Endpoints ---
    # User Registration
    path('api/v1/register/', community_views.UserRegistrationView.as_view(), name='user_register'),
    # Current User Details
    path('api/v1/user/me/', community_views.UserDetailView.as_view(), name='user_detail'),
    # User Profile by Username
    path('api/v1/user/<str:username>/', community_views.UserProfileView.as_view(), name='user_profile'),
    
    # SSO/OAuth Endpoints
    path('api/v1/auth/google/', community_views.google_oauth, name='google_oauth'),
    # Feedback endpoints (POST for anyone, GET list for staff)
    path('api/v1/feedback/', community_views.FeedbackView.as_view(), name='feedback'),
    
    # Includes all posts/comments URLs generated by the router
    path('api/v1/', include(router.urls)),
    
    # JWT Authentication Endpoints
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
]